server:
  port: 8091
  
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-test?autoreconnect=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.flywaydb: DEBUG

jwt:
  secret: "bGZwbzIwMDU="