server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-prod
    username: postgres2755
    password: postgres2222222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

